# -*- coding: utf-8 -*-
"""Reto4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cO6q8apylCfWZFIsJQ8E6lZvi81xlW3Y

Christian Nodal necesita ir a mercar y su padre le ha encargado una lista con los artículos a comprar. El supermercado al que él va tiene un programa de puntos por la compra de determinados productos, el cual está publicado en la entrada de la tienda. Christian desea conocer cuáles artículos de los que tiene en la lista están en el programa de puntos, y adicionalmente, cuántos puntos acumularía por los mismos. 

Entrada

La entrada consta de dos líneas. La primera línea contiene un diccionario en formato JSON con los productos que el supermercado ha dispuesto en su mercado de puntos, donde cada producto es una llave que contiene como valor puntos.  La segunda corresponde al listado de productos que se adquirirán en el supermercado, separados por un espacio. 

Salida

Dos líneas. La primera línea corresponde a los puntos acumulados de los productos de la lista de mercar que están en el programa de puntos. La segunda línea corresponde al listado de dichos productos, separados por un espacio. 

Entrada



{"Carne": 64, "Garbanzo": 88, "Fruta": 54, "Lenteja": 94, "Verdura": 66}

Fruta Leche Papa Huevos Carne
Salida
118

Fruta Carne

Entrada

{"Arroz": 77, "Frijol": 19, "Pescado": 68, "Verdura": 57, "Fruta": 41}

Huevos Carne Yogur Pollo Arroz

Salida

77

Arroz
"""

Listado_json=input("Ingrese el diccionario JSON con puntos")
compras=input("Ingrese la lista de compras del comprador")
Lista_compras=compras.split()
productos_con_puntos=[]
puntos=0
for articulo in Lista_compras:
  for (k,v) in Listado_json.items():
    if k==articulo:
      productos_con_puntos.append(k)
      puntos+=v
print(puntos)      
print(' '.join(productos_con_puntos))

# Commented out IPython magic to ensure Python compatibility.
# %reset