# -*- coding: utf-8 -*-
"""Reto 1 MisionTIC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ClsZihmelIf2WXXghNtF7JQYJ5eaVO5H

## RETO #1
## ELABORADO POR: DANIEL ANDRÉS DÁVILA LESMES

En una escena eliminada de Falcon and The Winter Soldier, Sam, Bucky y John Walker decidieron lanzar el escudo del Capitán América y ver qué tan lejos podría llegar si necesitaran atacar de lejos a alguien de los Flag Smashers. El escudo de Bucky fue el que más lejos llegó, su lanzamiento –luego de suprimir cuatro (4) metros- superó el doble de metros recorridos por el escudo de Sam. Mientras tanto, John Walker se siente frustrado porque la distancia que recorrió su lanzamiento es cinco veces menor que la suma de las distancias de Sam y Bucky.

Adicionalmente, el gobierno de Estados Unidos decidió categorizar estos lanzamientos. Si el escudo recorrió entre 0 y 20 metros, está en categoría uno, si está entre 21 y 30 metros en categoría dos, entre 31 y 50 metros se cataloga como categoría tres, y, por último, la categoría cuatro si es superior a los 50 metros. Esto con el fin de poder considerar la fuerza de nuestros héroes en el campo de batalla.

Elabore un programa que, dado el lanzamiento de Sam, muestre en la primera línea los metros recorridos para los lanzamientos de Sam, Bucky y John, separados por un espacio. Luego, en la segunda línea imprima en qué categoría quedó el lanzamiento de John Walker.

Entrada

La entrada es un número entero que representa la distancia en la que llegó el escudo lanzado por Sam.

Salida

Tres números enteros separados por un espacio que simbolizan las distancias de los lanzamientos de Sam, Bucky y John Walker. En la siguiente línea en letras la categoría del lanzamiento de John Walker.

Ejemplo

Entrada
14

Salida

14 32 9

uno
"""

#CÓDIGO PARA EL RETO 1
def categoria_lanzamiento(metros_Walker):
  if (metros_Walker>50):
    categoria= "cuatro"
  elif (31<=metros_Walker<=50):
    categoria="tres"
  elif (21<=metros_Walker<=30):
    categoria="dos"
  else:
    categoria="uno"
  return categoria

metros_Sam=int(input("En cifras enteras positivas ¿Cúantos metros alcanzó el lanzamiento de Sam? "))
metros_Bucky=((metros_Sam)*2)+4
metros_Walker=(metros_Bucky+metros_Sam)//5
print(metros_Sam,metros_Bucky,metros_Walker)
print(categoria_lanzamiento(metros_Walker))
#83,50,51,33,34,0