# -*- coding: utf-8 -*-
"""Reto 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DS38f5ChJYJeLMMzBnF3iqSt1fErVInW

En un torneo virtual de la oficina, Michael desea conocer las rachas que ha tenido en Mario Kart, en el que al final de cada carrera puede terminar en las posiciones 1 a 8. Michael ha anotado en qué posición ha quedado cada vez, y desea procesar estos resultados para ver su avance de forma simplificada. Al final obtiene dos listados, el primero en el que agrega una nueva posición solo si esta cambia y la segunda la cantidad de veces que ocurrió esa posición de forma consecutiva.

 

Ejemplo

Entrada:

4 4 5 4 3 3 3

 

Salida:

4 5 4 3

2 1 1 3

 

Michael agregó la posición 4, que se repitió dos veces.

Luego agregó la posición 5, que solo apareció una vez.

Agregó como nueva posición el 4° lugar, que sucedió una vez en ese instante.

Finalmente, aparece que terminó en la posición 3, que ocurrió 3 veces consecutivas.

 

Entrada

Listado de posiciones en los que llegó en cada carrera, separadas por un espacio.

 

Salida

Dos líneas: la primera línea representa las posiciones que ha obtenido separados por un espacio, y la segunda línea la cantidad de veces que se obtuvo esa posición de forma consecutiva.

 

Entrada

7 6 6 6 2 6 6 6 6 5 5 5 5

Salida

7 6 2 6 5                           
1 3 1 4 4
"""

def posiciones(lista):
  historico_posiciones=[]
  numero_ocurrencias=[]
  k=1
  for i in range (1,len(lista)): 
    xo= lista[i-1]
    x1=lista[i]
    if xo==x1:
      k+=1
    else:
      historico_posiciones.append(xo)
      numero_ocurrencias.append(str(k))
      k=1
  if x1 != historico_posiciones[-1]:
    historico_posiciones.append(x1)
    numero_ocurrencias.append(str(k))
  else:
    numero_ocurrencias[-1]+=k+1
  #hist=' '.join(historico_posiciones)
  print(' '.join(historico_posiciones))
  print(' '.join(numero_ocurrencias))
lista_posiciones=input("ingrese la lista de posiciones")
lista=lista_posiciones.split()
posiciones(lista)

# Commented out IPython magic to ensure Python compatibility.
# %reset