# -*- coding: utf-8 -*-
"""Reto 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J3o1sqLC6eWQooRcb7u5M65urrRrpPoR
"""

def Ataques(Ataques_Castle,Ataques_Fisk,Ataques_Presos):
  Cadena=""
  W=0
  C=0
  for ataque in Ataques_Presos:
    if (ataque in Ataques_Castle) and (ataque in Ataques_Fisk):
      C+=1
      W+=1
    elif ataque in Ataques_Fisk:
      W+=1
    elif ataque in Ataques_Castle:
      C+=1
    else:
      C+=0
      W+=0
    if C==W:
      Cadena+="-"
    elif C>W:
      Cadena+="C"
    else:
      Cadena+="W"
  return Cadena
Ataques_Castle= input("Por favor ingrese la cadena de ataques de Castle:")
Ataques_Fisk= input("Por favor ingrese la cadena de ataques de W Fisk:")
Ataques_Presos= input("Por favor ingrese la cadena de ataques de los presos:")
print(Ataques(Ataques_Castle,Ataques_Fisk,Ataques_Presos))
#BWOCVT
#JOIGED
#YNYJAVOLBQKNYKSZYG